### ISSUE TITLE
Página no HTML5

### ISSUE THREAD

**Issue by RafaSojo** [RafaSojo/2DAW-DWEC#24]
https://github.com/RafaSojo/2DAW-DWEC/blob/a082220a41f29c121ba78ad63b3c769810738cf1/ejercicios/tema2/ejercicio10/ejercicio.html#L4

Lo suyo sería tener todas las webs más o menos con la misma estructura y que estén en HTML 5.

**Comment by gboquizo** [comment]
Fixed by @alesjora  in e51abc50bea2aeaf03a08c22988bbcbc758aaf13 and merged in #31
