### ISSUE TITLE
Mal nombre de la carpeta 'practica 14'

### ISSUE THREAD

**Issue by RafaSojo** [RafaSojo/2DAW-DWEC#25]
La carpeta que se llama 'practica 14' debería llamarse 'ejercicio14' para seguir una nomenclatura común.

**Comment by RafaSojo** [comment]
La carpeta en cuestión es: https://github.com/RafaSojo/2DAW-DWEC/tree/master/ejercicios/tema2/practica%2014

**Comment by RafaSojo** [comment]
Además, están también mal el nombre de los ficheros en la carpeta.

**Comment by gboquizo** [comment]
Fixed by @angelobar  in e3ccc2b69a710ba82cded43519457f01044f1bcb and merged in #35
